users_accounts = [
    {
        "username": "SHALENGER",
        "email": "adhamibrahim20202024@gmail.com",
        "password": "A-D-H-A-M321",
        "birthday": "26/10/2012",
        "gender": "male",
        "age": 13,
        "phone": "01155169876",
    },
    {
        "username": "3naba",
        "email": "eyad3naba77@gmail.com",
        "password": "eyad146",
        "birthday": "7/5/2014",
        "gender": "male",
        "age": 11,
        "phone": "01154157371",
    },
    {
        "username": "sarah_ahmed",
        "email": "sarah.ahmed@gmail.com",
        "password": "sarah2024",
        "birthday": "15/3/2010",
        "gender": "female",
        "age": 16,
        "phone": "01098765432",
    },
    {
        "username": "mohamed_ali",
        "email": "mohamed.ali@outlook.com",
        "password": "mohamed123",
        "birthday": "22/8/2008",
        "gender": "male",
        "age": 18,
        "phone": "01234567890",
    },
    {
        "username": "layla_hassan",
        "email": "layla.hassan@yahoo.com",
        "password": "layla456",
        "birthday": "10/12/2011",
        "gender": "female",
        "age": 15,
        "phone": "01122334455",
    },
    {
        "username": "omar_khaled",
        "email": "omar.k@gmail.com",
        "password": "omar789",
        "birthday": "5/6/2013",
        "gender": "male",
        "age": 13,
        "phone": "01556677889",
    },
    {
        "username": "nour_mostafa",
        "email": "nour.mostafa@gmail.com",
        "password": "nour2024",
        "birthday": "18/1/2009",
        "gender": "female",
        "age": 17,
        "phone": "01099887766",
    },
]

courts_details = [
    # Football Courts
    {
        "name": "El-Itihad",
        "image 1": "images/football.jpeg",
        "image 2": "images/football.jpeg",
        "area": 150,
        "dimension": "50 x 25",
        "sport": "Football",
        "club": "El-Itihad",
        "price": "150/1h",
        "type": "indoor",
        "amenities": ["Parking", "Changing Rooms", "Showers", "Cafeteria"],
    },
    # Basketball Courts
    {
        "name": "El-47",
        "image 1": "images/basketball-outdoor.jpeg",
        "image 2": "images/basketball-indoor.jpeg",
        "area": 75,
        "dimension": "25 x 12.5",
        "sport": "basketball",
        "club": "EL-47",
        "price": "175/1h",
        "type": "outdoor",
        "amenities": ["Parking", "Water Fountain", "Benches", "Lighting"],
    },
    # Padel Courts
    {
        "name": "El-Ikhlas",
        "image 1": "images/padel.jpeg",
        "image 2": "images/padel.jpeg",
        "area": 80,
        "dimension": "25 x 15",
        "sport": "Padel",
        "club": "El-Ikhlas",
        "price": "200/1h",
        "type": "outdoor",
        "amenities": ["Parking", "Showers", "Equipment Rental", "WiFi"],
    },
    # Tennis Courts
    {
        "name": "El-Zikra",
        "image 1": "images/tennis-grass.jpeg",
        "image 2": "images/tennis-sand.jpeg",
        "area": 130,
        "dimension": "40 x 25",
        "sport": "tennis",
        "club": "EL-Zikra",
        "price": "250/1h",
        "type": "outdoor",
        "amenities": [
            "Parking",
            "Changing Rooms",
            "Equipment Rental",
            "Cafeteria",
            "WiFi",
        ],
    },
    # Volleyball Courts
    {
        "name": "El-Shehada",
        "image 1": "images/volleyball.jpeg",
        "image 2": "images/volleyball.jpeg",
        "area": 140,
        "dimension": "50 x 20",
        "sport": "volleyball",
        "club": "El-Shehada",
        "price": "200/1h",
        "type": "outdoor",
        "amenities": ["Parking", "Showers", "Benches", "Lighting"],
    },
    # Handball Courts
    {
        "name": "El-shark",
        "image 1": "images/handball.jpeg",
        "image 2": "images/handball.jpeg",
        "area": 140,
        "dimension": "50 x 25",
        "sport": "Handball",
        "club": "El-shark",
        "price": "125/1h",
        "type": "indoor",
        "amenities": ["Parking", "Changing Rooms", "Showers", "First Aid"],
    },
    # Additional Football Courts
    {
        "name": "El-Nasr Stadium",
        "image 1": "images/football.jpeg",
        "image 2": "images/football.jpeg",
        "area": 200,
        "dimension": "60 x 30",
        "sport": "Football",
        "club": "El-Nasr",
        "price": "200/1h",
        "type": "outdoor",
        "amenities": [
            "Parking",
            "Changing Rooms",
            "Showers",
            "Cafeteria",
            "Seating Area",
        ],
    },
    {
        "name": "Sporting Club",
        "image 1": "images/football.jpeg",
        "image 2": "images/football.jpeg",
        "area": 180,
        "dimension": "55 x 27",
        "sport": "Football",
        "club": "Sporting",
        "price": "175/1h",
        "type": "indoor",
        "amenities": [
            "Parking",
            "Changing Rooms",
            "Showers",
            "WiFi",
            "Air Conditioning",
        ],
    },
    # Additional Basketball Courts
    {
        "name": "El-Ahly Basketball",
        "image 1": "images/basketball-indoor.jpeg",
        "image 2": "images/basketball-outdoor.jpeg",
        "area": 80,
        "dimension": "28 x 15",
        "sport": "basketball",
        "club": "El-Ahly",
        "price": "200/1h",
        "type": "indoor",
        "amenities": ["Parking", "Changing Rooms", "Showers", "Scoreboard", "WiFi"],
    },
    {
        "name": "Youth Center Court",
        "image 1": "images/basketball-outdoor.jpeg",
        "image 2": "images/basketball-indoor.jpeg",
        "area": 70,
        "dimension": "26 x 14",
        "sport": "basketball",
        "club": "Youth Center",
        "price": "150/1h",
        "type": "outdoor",
        "amenities": ["Parking", "Water Fountain", "Benches"],
    },
    # Additional Padel Courts
    {
        "name": "Padel Pro",
        "image 1": "images/padel.jpeg",
        "image 2": "images/padel.jpeg",
        "area": 85,
        "dimension": "26 x 16",
        "sport": "Padel",
        "club": "Padel Pro",
        "price": "220/1h",
        "type": "indoor",
        "amenities": [
            "Parking",
            "Changing Rooms",
            "Showers",
            "Equipment Rental",
            "WiFi",
            "Air Conditioning",
        ],
    },
    {
        "name": "Elite Padel",
        "image 1": "images/padel.jpeg",
        "image 2": "images/padel.jpeg",
        "area": 80,
        "dimension": "25 x 15",
        "sport": "Padel",
        "club": "Elite Sports",
        "price": "190/1h",
        "type": "outdoor",
        "amenities": ["Parking", "Equipment Rental", "Cafeteria", "WiFi"],
    },
    # Additional Tennis Courts
    {
        "name": "Royal Tennis",
        "image 1": "images/tennis-sand.jpeg",
        "image 2": "images/tennis-grass.jpeg",
        "area": 135,
        "dimension": "42 x 26",
        "sport": "tennis",
        "club": "Royal Club",
        "price": "280/1h",
        "type": "outdoor",
        "amenities": [
            "Parking",
            "Changing Rooms",
            "Showers",
            "Equipment Rental",
            "Cafeteria",
            "WiFi",
            "Pro Shop",
        ],
    },
    {
        "name": "City Tennis Center",
        "image 1": "images/tennis-grass.jpeg",
        "image 2": "images/tennis-sand.jpeg",
        "area": 125,
        "dimension": "38 x 24",
        "sport": "tennis",
        "club": "City Sports",
        "price": "230/1h",
        "type": "indoor",
        "amenities": [
            "Parking",
            "Changing Rooms",
            "Showers",
            "Equipment Rental",
            "WiFi",
            "Air Conditioning",
        ],
    },
    # Additional Volleyball Courts
    {
        "name": "Beach Volleyball Arena",
        "image 1": "images/volleyball.jpeg",
        "image 2": "images/volleyball.jpeg",
        "area": 145,
        "dimension": "52 x 22",
        "sport": "volleyball",
        "club": "Beach Club",
        "price": "220/1h",
        "type": "outdoor",
        "amenities": ["Parking", "Showers", "Benches", "Lighting", "Sand Court"],
    },
    {
        "name": "Olympic Volleyball",
        "image 1": "images/volleyball.jpeg",
        "image 2": "images/volleyball.jpeg",
        "area": 150,
        "dimension": "54 x 24",
        "sport": "volleyball",
        "club": "Olympic Sports",
        "price": "210/1h",
        "type": "indoor",
        "amenities": [
            "Parking",
            "Changing Rooms",
            "Showers",
            "Scoreboard",
            "WiFi",
            "Air Conditioning",
        ],
    },
    # Additional Handball Courts
    {
        "name": "Champions Handball",
        "image 1": "images/handball.jpeg",
        "image 2": "images/handball.jpeg",
        "area": 145,
        "dimension": "52 x 26",
        "sport": "Handball",
        "club": "Champions Club",
        "price": "150/1h",
        "type": "indoor",
        "amenities": ["Parking", "Changing Rooms", "Showers", "First Aid", "WiFi"],
    },
    {
        "name": "Sporting Handball Arena",
        "image 1": "images/handball.jpeg",
        "image 2": "images/handball.jpeg",
        "area": 142,
        "dimension": "51 x 25",
        "sport": "Handball",
        "club": "Sporting",
        "price": "140/1h",
        "type": "outdoor",
        "amenities": ["Parking", "Benches", "Lighting", "First Aid"],
    },
]
